// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrGY4XTWDKKWyxpjykVqLW4-a1rOAdiZ0',
    appId: '1:770945556244:web:82f9685078b9e8395f2c01',
    messagingSenderId: '770945556244',
    projectId: 'classtrack-739e9',
    authDomain: 'classtrack-739e9.firebaseapp.com',
    storageBucket: 'classtrack-739e9.firebasestorage.app',
    measurementId: 'G-S1KGQ2334D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0HWod9llV1BXCkhk2EFOP9vzY9T3-Edk',
    appId: '1:770945556244:android:ffe33b3f9a2de3f75f2c01',
    messagingSenderId: '770945556244',
    projectId: 'classtrack-739e9',
    storageBucket: 'classtrack-739e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3jEu8456L5nDJz89mSa8Tra8QObg6X5E',
    appId: '1:770945556244:ios:8b51eddbb63278f65f2c01',
    messagingSenderId: '770945556244',
    projectId: 'classtrack-739e9',
    storageBucket: 'classtrack-739e9.firebasestorage.app',
    iosBundleId: 'com.example.classtrack',
  );
}
